# Generated by Django 5.2.1 on 2025-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_study_volunteer_status_studyvolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studyvolunteer',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_id',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
