# Generated by Django 5.2.1 on 2025-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_volunteer_phone_number_alter_studyvolunteer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='volunteers/'),
        ),
    ]
