# Generated by Django 5.2.1 on 2025-05-26 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_volunteer_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='study',
            name='date',
        ),
        migrations.AddField(
            model_name='study',
            name='assigned_staffs',
            field=models.ManyToManyField(blank=True, related_name='assigned_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('signed', 'Signed')], default='new', max_length=10),
        ),
    ]
