# Generated by Django 5.2.1 on 2025-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_remove_study_assigned_to_remove_study_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='created_at',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
