# Generated by Django 5.2.1 on 2025-05-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_study_study_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_name',
            field=models.CharField(max_length=100),
        ),
    ]
