# Generated by Django 5.2.1 on 2025-05-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_alter_study_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('finalized', 'Finalized')], default='Created', max_length=20),
        ),
    ]
