# Generated by Django 5.2.1 on 2025-05-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_alter_study_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='studies/'),
        ),
    ]
