# Generated by Django 5.2.1 on 2025-05-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_study_pdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyVolunteer',
        ),
    ]
