# Generated by Django 5.2.1 on 2025-05-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_delete_studyvolunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='Enrollments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.study')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'study')},
            },
        ),
    ]
