# Generated by Django 5.2.3 on 2025-07-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='LED', max_length=100)),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
    ]
