# Generated by Django 5.2.3 on 2025-07-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_logger', '0010_remove_device_auto_off_remove_device_auto_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='LED', max_length=100)),
                ('is_on', models.BooleanField(default=False)),
                ('schedule_on', models.BooleanField(default=False)),
                ('auto_on', models.TimeField(blank=True, null=True)),
                ('auto_off', models.TimeField(blank=True, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led', to='data_logger.device')),
            ],
        ),
    ]
