# Generated by Django 5.2.3 on 2025-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='led',
            name='auto_off',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='led',
            name='auto_on',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='led',
            name='schedule_on',
            field=models.BooleanField(default=False),
        ),
    ]
