# Generated by Django 5.2.3 on 2025-07-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='led',
            name='device',
        ),
    ]
