# Generated by Django 5.2.3 on 2025-07-01 09:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0003_autoreportschedule_delete_devicereading'),
        ('device_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 7, 1, 9, 55, 18, 827545))),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_logger.device')),
            ],
        ),
        migrations.DeleteModel(
            name='AutoReportSchedule',
        ),
    ]
