# Generated by Django 5.2.3 on 2025-07-01 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0002_devicereading_delete_autoreportschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereading',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 9, 55, 29, 927413)),
        ),
    ]
