# Generated by Django 5.2.3 on 2025-07-01 11:08

import data_logger.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0003_alter_devicereading_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereading',
            name='timestamp',
            field=models.DateTimeField(default=data_logger.utils.get_master_time),
        ),
    ]
