# Generated by Django 5.2.3 on 2025-07-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0010_remove_device_auto_off_remove_device_auto_on_and_more'),
        ('device_details', '0004_alter_devicereading_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Relay', max_length=50)),
                ('is_on', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='data_logger.device')),
            ],
        ),
    ]
