# Generated by Django 5.2.3 on 2025-07-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0005_devicecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='auto_off',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='auto_on',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='auto_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
