# Generated by Django 5.2.3 on 2025-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0006_devicecontrol_auto_off_devicecontrol_auto_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='auto_pause_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
