# Generated by Django 5.2.3 on 2025-07-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0007_devicecontrol_auto_pause_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='temp_control_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='temp_off_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecontrol',
            name='temp_on_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
