# Generated by Django 5.2.3 on 2025-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0008_devicecontrol_temp_control_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='control_priority',
            field=models.CharField(choices=[('schedule', 'Auto Schedule'), ('temp', 'Temperature Control')], default='schedule', help_text="Control priority: 'schedule' or 'temp'", max_length=10),
        ),
    ]
