# Generated by Django 5.2.3 on 2025-07-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0009_devicecontrol_control_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFeaturePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('priority', models.PositiveIntegerField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_priorities', to='device_details.devicecontrol')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('control', 'feature')},
            },
        ),
    ]
