# Generated by Django 5.2.3 on 2025-07-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0010_controlfeaturepriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='esp_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='ESP32 IP Address', null=True),
        ),
    ]
