# Generated by Django 5.2.3 on 2025-07-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_details', '0014_devicecontrol_confirmation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='last_confirmed_state',
            field=models.BooleanField(default=False),
        ),
    ]
