# Generated by Django 5.2.1 on 2025-05-24 18:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_difference', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('error', 'Error'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(blank=True, default=40, null=True)),
                ('min_temp', models.FloatField(blank=True, default=10, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('max_hum', models.FloatField(blank=True, default=70, null=True)),
                ('min_hum', models.FloatField(blank=True, default=20, null=True)),
                ('temp_sensor_error', models.BooleanField(default=False)),
                ('hum_sensor_error', models.BooleanField(default=False)),
                ('wifi_strength', models.IntegerField(blank=True, null=True)),
                ('rtc_error', models.BooleanField(default=False)),
                ('sd_card_error', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20)),
                ('firmware_url', models.URLField(blank=True, null=True)),
                ('last_calibrated', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_wifi', models.IntegerField(default=60)),
                ('interval_local', models.IntegerField(default=60)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('low_battery', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_logger.device')),
            ],
        ),
    ]
