# Generated by Django 5.2.3 on 2025-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='firmware_url',
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
