# Generated by Django 5.2.3 on 2025-07-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0003_autoreportschedule_delete_devicereading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoReportSchedule',
        ),
    ]
