# Generated by Django 5.2.3 on 2025-07-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0005_autoreportschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
