# Generated by Django 5.2.3 on 2025-07-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0007_led'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LED',
        ),
    ]
