# Generated by Django 5.2.3 on 2025-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0008_delete_led'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auto_off',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='auto_on',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='schedule_on',
            field=models.BooleanField(default=False),
        ),
    ]
