# Generated by Django 5.2.3 on 2025-07-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0009_device_auto_off_device_auto_on_device_is_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='auto_off',
        ),
        migrations.RemoveField(
            model_name='device',
            name='auto_on',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_on',
        ),
        migrations.RemoveField(
            model_name='device',
            name='schedule_on',
        ),
    ]
